### ISSUE TITLE
Unexpected last line in executable output

### ISSUE THREAD

**Issue by vadimtsushko** [filiph/dartbin#2]
On Windows I process simple hello world script

```
main(List<String> arguments) {
  print('Hello world');
}
```

Executable is created successfully, according by steps in README, but running executable I have following output:

```
C:\newproject\dartbin\go_src>go_src.exe
Hello world
2017/06/26 11:04:36 <nil>
```

Last line in the output probably should not appear at the normal circumstances?

**Comment by filiph** [comment]
Sorry, I thought I fixed this. Are you on the latest version (`git pull`)?

**Comment by vadimtsushko** [comment]
I've rechecked and yes, I'm still see this line with the current version of package, after git pull (git pull message is `Already up to date`)

**Comment by filiph** [comment]
Thanks for your patience. It was a stupid bug on my part. Should be fixed with https://github.com/filiph/dartbin/commit/28ac235764d06af79903e52b366ed7f6bfa59c7a. Feel free to reopen if it isn't.
